version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    restart: always
    command: ["mysqld", "--mysql-native-password=ON"]
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: project!_secret_root_password
      MYSQL_USER: project
      MYSQL_PASSWORD: project!_secret_password